fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    apache: "git://github.com/puppetlabs/puppetlabs-apache.git"
    apt:    "git://github.com/puppetlabs/puppetlabs-apt.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    nginx:
      repo: "git://github.com/jfryman/puppet-nginx.git"
      ref: "v0.0.10"
  symlinks:
    puppet_installer: "#{source_dir}"
