name          'danieldreier-puppet_installer'
version       '0.1.0'
source        'github.com/danieldreier/puppet-puppet_installer'
author        'Daniel Dreier'
license       'Apache 2.0'
summary       'Provide a curl|bash puppet install script for puppet masters'
description   ''
project_page  'https://github.com/danieldreier/puppet-puppet_installer'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/apache'
dependency 'jfryman/nginx'
